import { Product } from '@/components/product-card';

export const allProducts: Product[] = [
  {
    id: '1',
    name: 'Bonsai',
    category: 'Tanaman Hias Mini',
    description: 'Tanaman hias berukuran kecil yang dibentuk secara artistik. Cocok untuk dekorasi rumah dan memberikan kesan elegan.',
    difficulty: 'sedang',
    type: 'outdoor',
    status: 'tersedia',
    image: '/products/bonsai.jpeg',
    price: 150000,
  },
  {
    id: '2',
    name: 'Episcia',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan daun indah dan bunga kecil yang menarik. Cocok untuk area teduh dan ruangan lembap.',
    difficulty: 'mudah',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/episcia.jpeg',
    price: 35000,
  },
  {
    id: '3',
    name: 'Peperomia',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman mungil dengan bentuk daun unik dan menarik. Sangat cocok untuk meja kerja atau sudut ruangan.',
    difficulty: 'mudah',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/peperomia.jpeg',
    price: 45000,
  },
  {
    id: '4',
    name: 'Sekam Bakar',
    category: 'Media Tanam',
    description: 'Media tanam ringan yang membantu sirkulasi udara dan drainase akar. Cocok untuk campuran tanah berbagai jenis tanaman.',
    difficulty: 'mudah',
    type: 'keduanya',
    status: 'tersedia',
    image: '/products/sekam.jpeg',
    price: 12000,
  },
  {
    id: '5',
    name: 'Taiwan Putih',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan corak daun putih kehijauan yang menawan. Cocok untuk mempercantik ruangan dengan tampilan mewah.',
    difficulty: 'sedang',
    type: 'keduanya',
    status: 'tersedia',
    image: '/products/taiwan-putih.jpeg',
    price: 75000,
  },
  {
    id: '6',
    name: 'Aglaonema',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias populer dengan warna daun yang cantik dan beragam. Cocok untuk indoor karena tahan di tempat teduh.',
    difficulty: 'mudah',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/aglaonema.jpg',
    price: 55000,
  },
  {
    id: '7',
    name: 'Sansevieria',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias yang kuat, tahan lama, dan mudah dirawat. Cocok untuk pemula serta dapat ditempatkan indoor maupun outdoor.',
    difficulty: 'mudah',
    type: 'keduanya',
    status: 'tersedia',
    image: '/products/sansevieria.jpg',
    price: 45000,
  },
  {
    id: '8',
    name: 'Bonsai Beringin',
    category: 'Tanaman Hias Mini',
    description: 'Bonsai dengan bentuk batang dan tajuk yang indah, memberikan kesan klasik dan mewah untuk dekorasi rumah.',
    difficulty: 'sedang',
    type: 'outdoor',
    status: 'tersedia',
    image: '/products/bonsai-beringin.jpg',
    price: 175000,
  },
  {
    id: '9',
    name: 'Pellionia',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan daun kecil bercorak unik dan menjalar. Cocok untuk pot gantung atau dekorasi indoor yang estetik.',
    difficulty: 'mudah',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/pellionia.jpg',
    price: 40000,
  },
  {
    id: '10',
    name: 'Tradescantia Pallida',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan warna daun ungu mencolok yang sangat indah. Cocok untuk pot gantung maupun taman, dan mudah dirawat.',
    difficulty: 'mudah',
    type: 'keduanya',
    status: 'tersedia',
    image: '/products/tradescantia-pallida.jpg',
    price: 50000,
  },
  {
    id: '11',
    name: 'Bunga Krokot',
    category: 'Tanaman Hias Bunga',
    description: 'Tanaman hias berbunga dengan warna-warni cerah yang indah. Tahan panas dan cocok untuk taman outdoor maupun pot gantung.',
    difficulty: 'mudah',
    type: 'outdoor',
    status: 'tersedia',
    image: '/products/krokot.jpg',
    price: 15000,
  },
  {
    id: '12',
    name: 'Spathiphyllum (Peace Lily)',
    category: 'Tanaman Hias Bunga',
    description: 'Tanaman hias dengan bunga putih elegan yang memberikan kesan bersih dan tenang. Cocok untuk indoor dan membantu menyegarkan udara.',
    difficulty: 'mudah',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/spathiphyllum.jpg',
    price: 60000,
  },
  {
    id: '13',
    name: 'Anthurium',
    category: 'Tanaman Hias Bunga',
    description: 'Tanaman hias dengan bunga mengkilap berbentuk hati yang elegan. Cocok untuk indoor dan memberikan kesan mewah pada ruangan.',
    difficulty: 'sedang',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/anthurium.jpeg',
    price: 80000,
  },
  {
    id: '14',
    name: "Calathea Silver",
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan daun bercorak silver yang elegan dan unik. Cocok untuk indoor dengan pencahayaan tidak langsung.',
    difficulty: 'sedang',
    type: 'indoor',
    status: 'tersedia',
    image: '/products/calathea-silver.jpeg',
    price: 70000,
  },
  {
    id: '15',
    name: 'Tradescantia Spathacea',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman dengan daun hijau di atas dan ungu di bawah. Tahan panas dan cocok untuk indoor maupun outdoor.',
    difficulty: 'mudah',
    type: 'keduanya',
    status: 'tersedia',
    image: '/products/tradescantia-spathacea.jpeg',
    price: 40000,
  },
  {
    id: '16',
    name: 'Puring Bor',
    category: 'Tanaman Hias Daun',
    description: 'Tanaman hias dengan warna daun cerah dan beragam. Cocok untuk mempercantik taman outdoor dengan tampilan mencolok.',
    difficulty: 'mudah',
    type: 'outdoor',
    status: 'tersedia',
    image: '/products/puring-bor.jpeg',
    price: 50000,
  },
];